trigger:
- main

pool: dhurander

stages:
  - stage: 
    jobs:
      - job: 
        steps:
          
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/storage_account'
              backendServiceArm: 'dev-subcription'
              backendAzureRmStorageAccountName: 'azpipeline123'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'prod.terraform.tfstate'